### ISSUE TITLE
Java version is not detected correctly on macOS

### ISSUE THREAD

**Issue by anton-trunov** [EngineeringSoftware/mcoq#1]
Hi folks, thanks for the tool, I liked it a lot.

To test a project of mine I had to disable the function detecting the JDK version.
I'm using macOS and `openjdk` package installed via Homebrew.

Here is what `java -version` command outputs on my system:

```shell
$ java -version 2>&1
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```

**Comment by palmskog** [comment]
@anton-trunov Thanks for trying out the tool and for the report. One workaround to manually disabling the JDK version check is to just pass the option `--nocheck`, which should disable all dependency checking.

@kjain14 can you maybe take a look at fixing the Java version check in the Python code to support macOS as well?

**Comment by anton-trunov** [comment]
> One workaround to manually disabling the JDK version check is to just pass the option --nocheck, which should disable all dependency checking.

Oh, cool, thanks. I missed that and just hacked the script :)

**Comment by palmskog** [comment]
> I missed [`--nocheck`] and just hacked the script :)

Good to know. I modified the README to explicitly mention this option for others that may have similar problems.

**Comment by kjain14** [comment]
This is now fixed. Thanks for raising the issue.

**Comment by anton-trunov** [comment]
Sorry, after pulling the most recent changes from the repo it still says `Java is not installed, please install JDK.` if I don't add `--nocheck` option.

Thanks for looking into this.

**Comment by kjain14** [comment]
I was able to reproduce this issue on a Mac and pushed changes to fix it.

Please let me know if these changes work on your end.

**Comment by anton-trunov** [comment]
Works like a charm! Thank you.
